version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: python:3.6.1
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: docker build -t friendlyhelloangelo .
  deployment:
    hub:
      branch: master
      commands:
        - docker login -e angelo29goa@gmail.com -u angelo29goa -p fernandes29
        - docker push angelo29goa/friendlyhelloangelo