version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: python:3.6.1
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: docker build -t friendlyhelloangelo .
  deploy:
    working_directory: ~/app
    machine:
        enabled: true
    steps:
      - run: docker login -e angelo29goa@gmail.com -u angelo29goa -p fernandes29
      - run: docker push angelo29goa/friendlyhelloangelo